services:
    # React App

    db:
        image: mysql
        restart: always
        container_name: db
        environment:
            - MYSQL_ROOT_PASSWORD=123
            

    client:
        extends:
            file: docker-compose.base.yml
            service: app-base
        command: /bin/sh -c "cd ./packages/client && pnpm prod --host"
        
        depends_on:
            - api
        expose:
            - 4173

    api:
        extends:
            file: docker-compose.base.yml
            service: app-base
        environment:
            - DATABASE_URL=mysql://root:123@db:3306/prod
        command: /bin/sh -c "cd packages/core && node migrate-db.js && cd ../api && pnpm prod"
        depends_on:
            - db
        expose:
            - 3000

    # React App
    # app-2:
    #     extends:
    #         file: docker-compose.base.yml

    #         service: nx-app-base

    #     command: npm run app-2:dev:docker

    #     ports:
    #         - 4202:4200

    # # Angular App

    # app-3:
    #     extends:
    #         file: docker-compose.base.yml

    #         service: nx-app-base

    #     command: npm run app-3:dev:docker

    #     ports:
    #         - 4203:4200

    # # Express App

    # api-1:
    #     extends:
    #         file: docker-compose.base.yml

    #         service: nx-app-base

    #     command: npm run api-1:dev:docker

    #     ports:
    #         - 4310:3333 # API Entry port

    #         - 4311:4311 # Server Debugging port

volumes:
    mono-node-modules: null
