services:
    db:
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    project:
        build: .
        command: pnpm dev
        volumes:
            - .:/usr/app
        restart: always
